networks:
  default: 
    driver: bridge
    name: roboshop
  #external:true #we created network already using docker network create roboshop
services:
  mongodb:
    image: raheemrandy24/mongodb:v1
    container_name:  mongodb
  catalogue:
    image: raheemrandy24/catalogue:v1
    container_name:  catalogue
    depends_on:
    - mongodb
  redis:
    image: raheemrandy24/redis:v1
    container_name:  redis
  user:
    image: raheemrandy24/user:v1
    container_name:  user
    depends_on:
    - catalogue
    - redis
  cart:
    image: raheemrandy24/cart:v1
    container_name:  cart
    depends_on:
    - catalogue
    - redis 
  mysql:
    image: raheemrandy24/mysql:v1
    container_name:  mysql
  shipping:
    image: raheemrandy24/shipping:v1
    container_name:  shipping
    depends_on:
    - mysql
    - cart
  
   
